name: flutter_stripe_demo
description: Demo project showing Stripe Checkout integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  webview_flutter: ^4.10.0
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
